name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Build release
      run: cargo build --release --verbose
      
    - name: NixOS Build
      run: nix-shell -p crate2nix --command "crate2nix generate"
      
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Release title (for automatic releases)
        title: Automatic release
        # Assets to upload to the release
        files: |
          target/release/mrfetch
          Cargo.nix
        # Git tag
        automatic_release_tag: AUTO
        # Prerelease
        prerelease: true
        
